### ISSUE TITLE
Create experiment using CLI

### ISSUE THREAD

**Issue by utkarsh867** [deploifai/cli#8]
Proposal on the command spec to begin with:

```bash
deploifai experiment create --name <experiment_name> --project <username/project>
deploifai experiment create -n <experiment_name> -p <username/project>
```

Both short and long format for options to be made

**Comment by Richard-B18** [comment]
what does "--project <username/project>" mean?

`project` refers to project name, how about `username`?

**Comment by utkarsh867** [comment]
> what does `--project <username/project>` mean?
> 
> `project` refers to project name, how about `username`?

That would be the workspace. A user could be wanting to create an experiment in a project within their personal workspace, or a team workspace.

**Comment by Richard-B18** [comment]
so user has to specify both project name and workspace?

can user specify project name only if only one name exists across both personal and team workspaces?

**Comment by 98sean98** [comment]
I don't think `-p` for project / workspace specification for this command is necessary because the user who's doing experiments should have a project created already. Or the user should be invoking the project create command first. So the project where the experiment will live in should be taken from the local configuration file.

**Comment by Richard-B18** [comment]
should we assume that the user has the project created in their directory already? or user can just create experiments even if no single local projects exist locally

**Comment by 98sean98** [comment]
> should we assume that the user has the project created in their directory already? or user can just create experiments even if no single local projects exist locally

Yeah I think we could assume that.

**Comment by 98sean98** [comment]
For clarity:

A user should be able to create an experiment for `EXTERNAL` environment. In which case, the user merely has to provide an experiment name, as the project information would be read from a local configuration file.

A user should be able to create an experiment for `DEPLOIFAI` environment. In which case, the user is also prompted a list of existing training servers they need to choose to run the new experiment in. This command shouldn't involve any "create training server" step at all. An experiment should only run on a single training server. However, the user should be also be optionally prompted a list of existing datasets they want to connect to the training server, so that the experiment runs would have access to the datasets. An experiment can depend on multiple datasets. Right now the dataset connection step with a training server (after initial infrastructure orchestration of the training server) is still missing, see this [falcon issue](https://github.com/deploifai/falcon/issues/20).

**Comment by 98sean98** [comment]
Closed to clean up
