### ISSUE TITLE
setup go module for sdk development

### ISSUE THREAD

**Issue by 98sean98** [deploifai/cli#84]
`deploifai` python sdk is going to use `go` which takes advantage of compiling library api into executables. This means the sdk can be downloaded without any python cloud service APIs because they would have been included in the `go` built executables.

The binding between python and go can be accomplished by using [`gopy`](https://github.com/go-python/gopy).

**Comment by utkarsh867** [comment]
Started working on it recently.

I've decided to name the package `deploifai-sdk` and the import would work as such:
```py
import deploifai_sdk
from deploifai_sdk import api
```

Thinking to start with implementing the API since it seems like the lowest hanging fruit, and somehow solves one of the big issues we take with the Python version: zero type safety. 

The other advantage that we are chasing is reducing Python dependencies, which should speed up installation etc. The API implementation in Go will not necessarily reduce any dependencies at the moment, but implementation of other components like the cloud provider stuff will help.

**Comment by 98sean98** [comment]
It's better to just develop the python sdk purely in python, and rely on python dependencies for cloud provider sdks like `boto3`, etc.

There's also many incompatibilities between porting a go module to run in a python environment. So there's not really much scope in developing this vision any further.

**Comment by 98sean98** [comment]
Closed properly as not planned
